// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type AntrianLokal struct {
	ID         int64          `json:"id"`
	Jenis      string         `json:"jenis"`
	SubJenis   sql.NullString `json:"sub_jenis"`
	Nomor      string         `json:"nomor"`
	Prefix     string         `json:"prefix"`
	NoUrut     int64          `json:"no_urut"`
	NoRm       sql.NullString `json:"no_rm"`
	NoPoli     sql.NullString `json:"no_poli"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	SyncedAt   sql.NullTime   `json:"synced_at"`
	SyncStatus sql.NullString `json:"sync_status"`
}

type ConfigCache struct {
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type PendingSep struct {
	ID             int64          `json:"id"`
	NoKartu        string         `json:"no_kartu"`
	Kategori       string         `json:"kategori"`
	PayloadJson    string         `json:"payload_json"`
	VclaimResponse sql.NullString `json:"vclaim_response"`
	Status         sql.NullString `json:"status"`
	RetryCount     sql.NullInt64  `json:"retry_count"`
	LastError      sql.NullString `json:"last_error"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	ConfirmedBy    sql.NullString `json:"confirmed_by"`
	ConfirmedAt    sql.NullTime   `json:"confirmed_at"`
}

type PrintHistory struct {
	ID           int64          `json:"id"`
	DocType      string         `json:"doc_type"`
	RefID        sql.NullString `json:"ref_id"`
	EscposBytes  []byte         `json:"escpos_bytes"`
	PrintedAt    sql.NullTime   `json:"printed_at"`
	ReprintCount sql.NullInt64  `json:"reprint_count"`
}

type ReconcileLog struct {
	ID         int64          `json:"id"`
	TableName  string         `json:"table_name"`
	RecordID   int64          `json:"record_id"`
	Action     string         `json:"action"`
	OperatorID sql.NullString `json:"operator_id"`
	Result     sql.NullString `json:"result"`
	Timestamp  sql.NullTime   `json:"timestamp"`
}
