// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	ConfirmSEP(ctx context.Context, arg ConfirmSEPParams) error
	// Reset counter harian -- hapus semua entry hari ini.
	// Dipakai oleh AntrianService.ResetAll (cron 00:01 atau manual admin).
	DeleteAntrianToday(ctx context.Context) (int64, error)
	// Counter offline per jenis: nomor terbesar yang sudah pernah dikeluarkan
	// HARI INI. 0 jika belum ada -- caller add 1 untuk next.
	//
	// CATATAN created_at sudah disimpan sebagai localtime via schema
	// DEFAULT (datetime('now','localtime')). JANGAN tambah modifier
	// 'localtime' di sini karena akan double-shift (treat as UTC + apply
	// offset lagi) -- bug yang menyebabkan test fail setelah jam 17 WIB.
	GetMaxNoUrutToday(ctx context.Context, jenis string) (int64, error)
	GetPendingAntrian(ctx context.Context, limit int64) ([]AntrianLokal, error)
	GetPendingSEPs(ctx context.Context, arg GetPendingSEPsParams) ([]PendingSep, error)
	GetPrintHistory(ctx context.Context, id int64) (PrintHistory, error)
	GetPrintHistoryByRefID(ctx context.Context, arg GetPrintHistoryByRefIDParams) (PrintHistory, error)
	// Tiebreaker id DESC karena datetime('now','localtime') hanya resolusi detik,
	// multiple insert dalam detik yang sama bisa punya timestamp identik.
	GetRecentLogs(ctx context.Context, limit int64) ([]ReconcileLog, error)
	IncrementReprintCount(ctx context.Context, id int64) error
	IncrementSEPRetry(ctx context.Context, arg IncrementSEPRetryParams) error
	// ============================================================
	// antrian_lokal -- buffer offline antrian
	// ============================================================
	InsertAntrian(ctx context.Context, arg InsertAntrianParams) (AntrianLokal, error)
	// ============================================================
	// pending_sep -- SEP yang menunggu sync ke Khanza
	// ============================================================
	InsertPendingSEP(ctx context.Context, arg InsertPendingSEPParams) (PendingSep, error)
	// ============================================================
	// print_history -- log dokumen yang dicetak (untuk reprint)
	// ============================================================
	InsertPrintHistory(ctx context.Context, arg InsertPrintHistoryParams) (PrintHistory, error)
	// ============================================================
	// reconcile_log -- audit trail
	// ============================================================
	InsertReconcileLog(ctx context.Context, arg InsertReconcileLogParams) (ReconcileLog, error)
	MarkAntrianFailed(ctx context.Context, id int64) error
	MarkAntrianSynced(ctx context.Context, id int64) error
	MarkSEPSynced(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
