// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	ConfirmSEP(ctx context.Context, arg ConfirmSEPParams) error
	GetPendingAntrian(ctx context.Context, limit int64) ([]AntrianLokal, error)
	GetPendingSEPs(ctx context.Context, arg GetPendingSEPsParams) ([]PendingSep, error)
	GetPrintHistory(ctx context.Context, id int64) (PrintHistory, error)
	GetPrintHistoryByRefID(ctx context.Context, arg GetPrintHistoryByRefIDParams) (PrintHistory, error)
	// Tiebreaker id DESC karena datetime('now','localtime') hanya resolusi detik,
	// multiple insert dalam detik yang sama bisa punya timestamp identik.
	GetRecentLogs(ctx context.Context, limit int64) ([]ReconcileLog, error)
	IncrementReprintCount(ctx context.Context, id int64) error
	IncrementSEPRetry(ctx context.Context, arg IncrementSEPRetryParams) error
	// ============================================================
	// antrian_lokal -- buffer offline antrian
	// ============================================================
	InsertAntrian(ctx context.Context, arg InsertAntrianParams) (AntrianLokal, error)
	// ============================================================
	// pending_sep -- SEP yang menunggu sync ke Khanza
	// ============================================================
	InsertPendingSEP(ctx context.Context, arg InsertPendingSEPParams) (PendingSep, error)
	// ============================================================
	// print_history -- log dokumen yang dicetak (untuk reprint)
	// ============================================================
	InsertPrintHistory(ctx context.Context, arg InsertPrintHistoryParams) (PrintHistory, error)
	// ============================================================
	// reconcile_log -- audit trail
	// ============================================================
	InsertReconcileLog(ctx context.Context, arg InsertReconcileLogParams) (ReconcileLog, error)
	MarkAntrianFailed(ctx context.Context, id int64) error
	MarkAntrianSynced(ctx context.Context, id int64) error
	MarkSEPSynced(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
