// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const confirmSEP = `-- name: ConfirmSEP :exec
UPDATE pending_sep
SET status       = 'awaiting_sync',
    confirmed_by = ?,
    confirmed_at = datetime('now','localtime')
WHERE id = ?
`

type ConfirmSEPParams struct {
	ConfirmedBy sql.NullString `json:"confirmed_by"`
	ID          int64          `json:"id"`
}

func (q *Queries) ConfirmSEP(ctx context.Context, arg ConfirmSEPParams) error {
	_, err := q.db.ExecContext(ctx, confirmSEP, arg.ConfirmedBy, arg.ID)
	return err
}

const getPendingAntrian = `-- name: GetPendingAntrian :many
SELECT id, jenis, sub_jenis, nomor, prefix, no_urut, no_rm, no_poli, created_at, synced_at, sync_status
FROM antrian_lokal
WHERE sync_status = 'pending'
ORDER BY created_at ASC
LIMIT ?
`

func (q *Queries) GetPendingAntrian(ctx context.Context, limit int64) ([]AntrianLokal, error) {
	rows, err := q.db.QueryContext(ctx, getPendingAntrian, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AntrianLokal{}
	for rows.Next() {
		var i AntrianLokal
		if err := rows.Scan(
			&i.ID,
			&i.Jenis,
			&i.SubJenis,
			&i.Nomor,
			&i.Prefix,
			&i.NoUrut,
			&i.NoRm,
			&i.NoPoli,
			&i.CreatedAt,
			&i.SyncedAt,
			&i.SyncStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingSEPs = `-- name: GetPendingSEPs :many
SELECT id, no_kartu, kategori, payload_json, vclaim_response, status, retry_count, last_error, created_at, confirmed_by, confirmed_at
FROM pending_sep
WHERE status = ?
ORDER BY created_at ASC
LIMIT ?
`

type GetPendingSEPsParams struct {
	Status sql.NullString `json:"status"`
	Limit  int64          `json:"limit"`
}

func (q *Queries) GetPendingSEPs(ctx context.Context, arg GetPendingSEPsParams) ([]PendingSep, error) {
	rows, err := q.db.QueryContext(ctx, getPendingSEPs, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingSep{}
	for rows.Next() {
		var i PendingSep
		if err := rows.Scan(
			&i.ID,
			&i.NoKartu,
			&i.Kategori,
			&i.PayloadJson,
			&i.VclaimResponse,
			&i.Status,
			&i.RetryCount,
			&i.LastError,
			&i.CreatedAt,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrintHistory = `-- name: GetPrintHistory :one
SELECT id, doc_type, ref_id, escpos_bytes, printed_at, reprint_count
FROM print_history
WHERE id = ?
`

func (q *Queries) GetPrintHistory(ctx context.Context, id int64) (PrintHistory, error) {
	row := q.db.QueryRowContext(ctx, getPrintHistory, id)
	var i PrintHistory
	err := row.Scan(
		&i.ID,
		&i.DocType,
		&i.RefID,
		&i.EscposBytes,
		&i.PrintedAt,
		&i.ReprintCount,
	)
	return i, err
}

const getPrintHistoryByRefID = `-- name: GetPrintHistoryByRefID :one
SELECT id, doc_type, ref_id, escpos_bytes, printed_at, reprint_count
FROM print_history
WHERE doc_type = ? AND ref_id = ?
ORDER BY printed_at DESC
LIMIT 1
`

type GetPrintHistoryByRefIDParams struct {
	DocType string         `json:"doc_type"`
	RefID   sql.NullString `json:"ref_id"`
}

func (q *Queries) GetPrintHistoryByRefID(ctx context.Context, arg GetPrintHistoryByRefIDParams) (PrintHistory, error) {
	row := q.db.QueryRowContext(ctx, getPrintHistoryByRefID, arg.DocType, arg.RefID)
	var i PrintHistory
	err := row.Scan(
		&i.ID,
		&i.DocType,
		&i.RefID,
		&i.EscposBytes,
		&i.PrintedAt,
		&i.ReprintCount,
	)
	return i, err
}

const getRecentLogs = `-- name: GetRecentLogs :many
SELECT id, table_name, record_id, "action", operator_id, result, timestamp
FROM reconcile_log
ORDER BY timestamp DESC, id DESC
LIMIT ?
`

// Tiebreaker id DESC karena datetime('now','localtime') hanya resolusi detik,
// multiple insert dalam detik yang sama bisa punya timestamp identik.
func (q *Queries) GetRecentLogs(ctx context.Context, limit int64) ([]ReconcileLog, error) {
	rows, err := q.db.QueryContext(ctx, getRecentLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconcileLog{}
	for rows.Next() {
		var i ReconcileLog
		if err := rows.Scan(
			&i.ID,
			&i.TableName,
			&i.RecordID,
			&i.Action,
			&i.OperatorID,
			&i.Result,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementReprintCount = `-- name: IncrementReprintCount :exec
UPDATE print_history
SET reprint_count = reprint_count + 1
WHERE id = ?
`

func (q *Queries) IncrementReprintCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementReprintCount, id)
	return err
}

const incrementSEPRetry = `-- name: IncrementSEPRetry :exec
UPDATE pending_sep
SET retry_count = retry_count + 1,
    last_error  = ?
WHERE id = ?
`

type IncrementSEPRetryParams struct {
	LastError sql.NullString `json:"last_error"`
	ID        int64          `json:"id"`
}

func (q *Queries) IncrementSEPRetry(ctx context.Context, arg IncrementSEPRetryParams) error {
	_, err := q.db.ExecContext(ctx, incrementSEPRetry, arg.LastError, arg.ID)
	return err
}

const insertAntrian = `-- name: InsertAntrian :one

INSERT INTO antrian_lokal (jenis, sub_jenis, nomor, prefix, no_urut, no_rm, no_poli)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, jenis, sub_jenis, nomor, prefix, no_urut, no_rm, no_poli, created_at, synced_at, sync_status
`

type InsertAntrianParams struct {
	Jenis    string         `json:"jenis"`
	SubJenis sql.NullString `json:"sub_jenis"`
	Nomor    string         `json:"nomor"`
	Prefix   string         `json:"prefix"`
	NoUrut   int64          `json:"no_urut"`
	NoRm     sql.NullString `json:"no_rm"`
	NoPoli   sql.NullString `json:"no_poli"`
}

// ============================================================
// antrian_lokal -- buffer offline antrian
// ============================================================
func (q *Queries) InsertAntrian(ctx context.Context, arg InsertAntrianParams) (AntrianLokal, error) {
	row := q.db.QueryRowContext(ctx, insertAntrian,
		arg.Jenis,
		arg.SubJenis,
		arg.Nomor,
		arg.Prefix,
		arg.NoUrut,
		arg.NoRm,
		arg.NoPoli,
	)
	var i AntrianLokal
	err := row.Scan(
		&i.ID,
		&i.Jenis,
		&i.SubJenis,
		&i.Nomor,
		&i.Prefix,
		&i.NoUrut,
		&i.NoRm,
		&i.NoPoli,
		&i.CreatedAt,
		&i.SyncedAt,
		&i.SyncStatus,
	)
	return i, err
}

const insertPendingSEP = `-- name: InsertPendingSEP :one

INSERT INTO pending_sep (no_kartu, kategori, payload_json, vclaim_response)
VALUES (?, ?, ?, ?)
RETURNING id, no_kartu, kategori, payload_json, vclaim_response, status, retry_count, last_error, created_at, confirmed_by, confirmed_at
`

type InsertPendingSEPParams struct {
	NoKartu        string         `json:"no_kartu"`
	Kategori       string         `json:"kategori"`
	PayloadJson    string         `json:"payload_json"`
	VclaimResponse sql.NullString `json:"vclaim_response"`
}

// ============================================================
// pending_sep -- SEP yang menunggu sync ke Khanza
// ============================================================
func (q *Queries) InsertPendingSEP(ctx context.Context, arg InsertPendingSEPParams) (PendingSep, error) {
	row := q.db.QueryRowContext(ctx, insertPendingSEP,
		arg.NoKartu,
		arg.Kategori,
		arg.PayloadJson,
		arg.VclaimResponse,
	)
	var i PendingSep
	err := row.Scan(
		&i.ID,
		&i.NoKartu,
		&i.Kategori,
		&i.PayloadJson,
		&i.VclaimResponse,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
	)
	return i, err
}

const insertPrintHistory = `-- name: InsertPrintHistory :one

INSERT INTO print_history (doc_type, ref_id, escpos_bytes)
VALUES (?, ?, ?)
RETURNING id, doc_type, ref_id, escpos_bytes, printed_at, reprint_count
`

type InsertPrintHistoryParams struct {
	DocType     string         `json:"doc_type"`
	RefID       sql.NullString `json:"ref_id"`
	EscposBytes []byte         `json:"escpos_bytes"`
}

// ============================================================
// print_history -- log dokumen yang dicetak (untuk reprint)
// ============================================================
func (q *Queries) InsertPrintHistory(ctx context.Context, arg InsertPrintHistoryParams) (PrintHistory, error) {
	row := q.db.QueryRowContext(ctx, insertPrintHistory, arg.DocType, arg.RefID, arg.EscposBytes)
	var i PrintHistory
	err := row.Scan(
		&i.ID,
		&i.DocType,
		&i.RefID,
		&i.EscposBytes,
		&i.PrintedAt,
		&i.ReprintCount,
	)
	return i, err
}

const insertReconcileLog = `-- name: InsertReconcileLog :one

INSERT INTO reconcile_log (table_name, record_id, action, operator_id, result)
VALUES (?, ?, ?, ?, ?)
RETURNING id, table_name, record_id, "action", operator_id, result, timestamp
`

type InsertReconcileLogParams struct {
	TableName  string         `json:"table_name"`
	RecordID   int64          `json:"record_id"`
	Action     string         `json:"action"`
	OperatorID sql.NullString `json:"operator_id"`
	Result     sql.NullString `json:"result"`
}

// ============================================================
// reconcile_log -- audit trail
// ============================================================
func (q *Queries) InsertReconcileLog(ctx context.Context, arg InsertReconcileLogParams) (ReconcileLog, error) {
	row := q.db.QueryRowContext(ctx, insertReconcileLog,
		arg.TableName,
		arg.RecordID,
		arg.Action,
		arg.OperatorID,
		arg.Result,
	)
	var i ReconcileLog
	err := row.Scan(
		&i.ID,
		&i.TableName,
		&i.RecordID,
		&i.Action,
		&i.OperatorID,
		&i.Result,
		&i.Timestamp,
	)
	return i, err
}

const markAntrianFailed = `-- name: MarkAntrianFailed :exec
UPDATE antrian_lokal
SET sync_status = 'failed'
WHERE id = ?
`

func (q *Queries) MarkAntrianFailed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markAntrianFailed, id)
	return err
}

const markAntrianSynced = `-- name: MarkAntrianSynced :exec
UPDATE antrian_lokal
SET sync_status = 'synced',
    synced_at   = datetime('now','localtime')
WHERE id = ?
`

func (q *Queries) MarkAntrianSynced(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markAntrianSynced, id)
	return err
}

const markSEPSynced = `-- name: MarkSEPSynced :exec
UPDATE pending_sep
SET status = 'synced'
WHERE id = ?
`

func (q *Queries) MarkSEPSynced(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markSEPSynced, id)
	return err
}
