// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {main} from '../models';
import {store} from '../models';

export function BuatPendaftaran(arg1:domain.PendaftaranRequest):Promise<domain.Pendaftaran>;

export function BuatSEPKontrol(arg1:string,arg2:string):Promise<domain.SEP>;

export function BuatSEPPostRAJAL(arg1:string,arg2:string):Promise<domain.SEP>;

export function BuatSEPPostRANAP(arg1:string,arg2:string):Promise<domain.SEP>;

export function BuatSEPRujukan(arg1:domain.SEPRequest):Promise<domain.SEP>;

export function CariPasien(arg1:string):Promise<domain.Pasien>;

export function ConfirmSEPSync(arg1:number):Promise<void>;

export function CreateAntrian(arg1:string,arg2:string):Promise<domain.Ticket>;

export function DetectPatient(arg1:string):Promise<domain.DetectionResult>;

export function GetAdminStats():Promise<main.AdminStats>;

export function GetBranding():Promise<main.Branding>;

export function GetCounters():Promise<Record<string, number>>;

export function GetHardwareStatus():Promise<main.HardwareStatus>;

export function GetJadwalDokter(arg1:string):Promise<Array<domain.JadwalDokter>>;

export function GetPendingSEPs():Promise<Array<store.PendingSep>>;

export function GetPoliklinikAktif():Promise<Array<domain.Poliklinik>>;

export function GetRecentLogs(arg1:number):Promise<Array<main.AdminLogEntry>>;

export function GetSystemStatus():Promise<main.SystemStatus>;

export function Greet(arg1:string):Promise<string>;

export function Reprint(arg1:number):Promise<void>;

export function ResetCounters():Promise<void>;

export function ResetSession():Promise<void>;

export function RunStartupChecks():Promise<Array<main.CheckResult>>;

export function TestPrint():Promise<void>;

export function VerifikasiSidikJari(arg1:string):Promise<string>;

export function VerifikasiWajah(arg1:string):Promise<string>;

export function VerifyAdminPIN(arg1:string):Promise<boolean>;
