// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuatPendaftaran(arg1) {
  return window['go']['main']['App']['BuatPendaftaran'](arg1);
}

export function BuatSEPKontrol(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuatSEPKontrol'](arg1, arg2, arg3);
}

export function BuatSEPPostRAJAL(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuatSEPPostRAJAL'](arg1, arg2, arg3);
}

export function BuatSEPPostRANAP(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuatSEPPostRANAP'](arg1, arg2, arg3);
}

export function BuatSEPRujukan(arg1) {
  return window['go']['main']['App']['BuatSEPRujukan'](arg1);
}

export function CariPasien(arg1) {
  return window['go']['main']['App']['CariPasien'](arg1);
}

export function ConfirmSEPSync(arg1) {
  return window['go']['main']['App']['ConfirmSEPSync'](arg1);
}

export function CreateAntrian(arg1, arg2) {
  return window['go']['main']['App']['CreateAntrian'](arg1, arg2);
}

export function DetectPatient(arg1) {
  return window['go']['main']['App']['DetectPatient'](arg1);
}

export function GetAdminStats() {
  return window['go']['main']['App']['GetAdminStats']();
}

export function GetBranding() {
  return window['go']['main']['App']['GetBranding']();
}

export function GetCounters() {
  return window['go']['main']['App']['GetCounters']();
}

export function GetHardwareStatus() {
  return window['go']['main']['App']['GetHardwareStatus']();
}

export function GetJadwalDokter(arg1) {
  return window['go']['main']['App']['GetJadwalDokter'](arg1);
}

export function GetPendingSEPs() {
  return window['go']['main']['App']['GetPendingSEPs']();
}

export function GetPoliklinikAktif() {
  return window['go']['main']['App']['GetPoliklinikAktif']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetSystemStatus() {
  return window['go']['main']['App']['GetSystemStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Reprint(arg1) {
  return window['go']['main']['App']['Reprint'](arg1);
}

export function ResetCounters() {
  return window['go']['main']['App']['ResetCounters']();
}

export function ResetSession() {
  return window['go']['main']['App']['ResetSession']();
}

export function RunStartupChecks() {
  return window['go']['main']['App']['RunStartupChecks']();
}

export function TestPrint() {
  return window['go']['main']['App']['TestPrint']();
}

export function VerifikasiSidikJari(arg1) {
  return window['go']['main']['App']['VerifikasiSidikJari'](arg1);
}

export function VerifikasiWajah(arg1) {
  return window['go']['main']['App']['VerifikasiWajah'](arg1);
}

export function PengajuanSEPFP(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PengajuanSEPFP'](arg1, arg2, arg3, arg4);
}

export function AprovalSEPFP(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AprovalSEPFP'](arg1, arg2, arg3, arg4);
}

export function VerifyAdminPIN(arg1) {
  return window['go']['main']['App']['VerifyAdminPIN'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CancelAutoApplyUpdate() {
  return window['go']['main']['App']['CancelAutoApplyUpdate']();
}

export function RollbackUpdate() {
  return window['go']['main']['App']['RollbackUpdate']();
}
